server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth-ms
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
api:
  auth:
    secret: 62e360a697e64542a5d27f07048ffcf2
eureka:
  instance:
    hostname: localhosts
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/registry/eureka

# Springdoc OpenApi 3.1 & Swagger 3
springdoc:
  packagesToScan: br.com.grimorium.authms.controller
  swagger-ui:
    path: /docs-grimorium.html
  api-docs:
    path: /docs-grimorium
